Repository bizz84/SwiftyStoreKit, pull requests merged in 2020-03, with the labels that each got.

#524 Creating a Code of Conduct
  CODE_OF_CONDUCT.md
Labels: help wanted, status: needs analysis, type: enhancement

#441 Add Purchased Protocol
  SwiftyStoreKit/SwiftyStoreKit+Types.swift
Labels: area: purchase flows, status: code review, type: enhancement

#499 Added support for Subscription Offers
  SwiftyStoreKit/PaymentQueueController.swift
  SwiftyStoreKit/PaymentsController.swift
  SwiftyStoreKit/SwiftyStoreKit.swift
  SwiftyStoreKitTests/PaymentQueueControllerTests.swift
  SwiftyStoreKitTests/PaymentsControllerTests.swift
Labels: area: new technologies, area: purchase flows, type: enhancement

#465 Resolved repurchasing a non-consumable not calling completion, on macOS
  SwiftyStoreKit/PaymentsController.swift
Labels: area: purchase flows, status: needs analysis, type: bug
